import * as React from 'react';

interface SaveChartProps {
  name: string;
  total: number;
  method: string;
  letters: Array<{ letter: string; value: number }>;
}

export function SaveChart({ name, total, method, letters }: SaveChartProps) {
  const [saved, setSaved] = React.useState(false);

  const methodLabel = (m: string) => {
    switch (m) {
      case 'standard': return 'Standard';
      case 'ordinal': return 'Ordinal';
      case 'reduced': return 'Reduced';
      case 'integral': return 'Integral Reduced';
      default: return m;
    }
  };

  const saveAsText = () => {
    const lines = [
      '═══════════════════════════════════',
      '        ✨ MysticMinded³³ ✨',
      '     Gematria Chart Result',
      '═══════════════════════════════════',
      `Name: ${name}`,
      `Method: ${methodLabel(method)}`,
      `Total Value: ${total}`,
      '───────────────────────────────────',
      'Letter Breakdown:',
      ...letters.map(l => `  ${l.letter}  →  ${l.value}`),
      '───────────────────────────────────',
      `Generated by MysticMinded³³`,
      `${new Date().toLocaleDateString()}`,
      '═══════════════════════════════════',
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `gematria-${name}-${total}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    setSaved(true);
    setTimeout(() => setSaved(false), 2000);
  };

  const saveAsImage = () => {
    const canvas = document.createElement('canvas');
    canvas.width = 500;
    canvas.height = Math.max(400, 200 + letters.length * 28);
    const ctx = canvas.getContext('2d')!;

    // Background
    const grad = ctx.createLinearGradient(0, 0, 0, canvas.height);
    grad.addColorStop(0, '#1a0a2e');
    grad.addColorStop(1, '#2d1b4e');
    ctx.fillStyle = grad;
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    // Gold border
    ctx.strokeStyle = '#c9a84c';
    ctx.lineWidth = 3;
    ctx.strokeRect(10, 10, canvas.width - 20, canvas.height - 20);

    // Title
    ctx.fillStyle = '#c9a84c';
    ctx.font = 'bold 22px Georgia';
    ctx.textAlign = 'center';
    ctx.fillText('✨ MysticMinded³³ ✨', canvas.width / 2, 55);

    ctx.fillStyle = '#a07cc5';
    ctx.font = '14px Georgia';
    ctx.fillText('Gematria Chart', canvas.width / 2, 80);

    // Divider
    ctx.strokeStyle = 'rgba(201,168,76,0.4)';
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(40, 95);
    ctx.lineTo(460, 95);
    ctx.stroke();

    // Name & total
    ctx.fillStyle = '#e8d5ff';
    ctx.font = 'bold 18px Georgia';
    ctx.textAlign = 'left';
    ctx.fillText(`Name: ${name}`, 40, 125);
    ctx.font = '14px Georgia';
    ctx.fillStyle = '#a07cc5';
    ctx.fillText(`Method: ${methodLabel(method)}`, 40, 150);

    ctx.fillStyle = '#c9a84c';
    ctx.font = 'bold 36px Georgia';
    ctx.textAlign = 'right';
    ctx.fillText(`${total}`, 460, 145);
    ctx.font = '12px Georgia';
    ctx.fillStyle = '#a07cc5';
    ctx.fillText('Total Value', 460, 162);

    // Divider
    ctx.strokeStyle = 'rgba(201,168,76,0.4)';
    ctx.beginPath();
    ctx.moveTo(40, 175);
    ctx.lineTo(460, 175);
    ctx.stroke();

    // Letters
    ctx.fillStyle = '#c9a84c';
    ctx.font = 'bold 13px Georgia';
    ctx.textAlign = 'left';
    ctx.fillText('Letter Breakdown:', 40, 200);

    letters.forEach((l, i) => {
      const y = 225 + i * 26;
      ctx.fillStyle = i % 2 === 0 ? 'rgba(255,255,255,0.05)' : 'transparent';
      ctx.fillRect(40, y - 16, 420, 24);
      ctx.fillStyle = '#e8d5ff';
      ctx.font = '15px Georgia';
      ctx.textAlign = 'left';
      ctx.fillText(l.letter, 55, y);
      ctx.fillStyle = '#c9a84c';
      ctx.font = 'bold 15px Georgia';
      ctx.textAlign = 'right';
      ctx.fillText(`${l.value}`, 460, y);
    });

    // Footer
    ctx.fillStyle = 'rgba(201,168,76,0.5)';
    ctx.font = '11px Georgia';
    ctx.textAlign = 'center';
    ctx.fillText(`mysticminded33.com  •  ${new Date().toLocaleDateString()}`, canvas.width / 2, canvas.height - 20);

    canvas.toBlob(blob => {
      const url = URL.createObjectURL(blob!);
      const a = document.createElement('a');
      a.href = url;
      a.download = `gematria-${name}-${total}.png`;
      a.click();
      URL.revokeObjectURL(url);
    });
    setSaved(true);
    setTimeout(() => setSaved(false), 2000);
  };

  const btnStyle = (bg: string): React.CSSProperties => ({
    display: 'flex', alignItems: 'center', gap: '6px',
    padding: '8px 14px', borderRadius: '20px', border: 'none',
    background: bg, color: '#fff', fontWeight: 'bold',
    fontSize: '13px', cursor: 'pointer', whiteSpace: 'nowrap',
    boxShadow: '0 2px 8px rgba(0,0,0,0.15)', transition: 'opacity 0.2s',
  });

  return (
    <div style={{
      margin: '8px 0 12px 0',
      padding: '12px 16px',
      background: 'linear-gradient(135deg, rgba(26,10,46,0.06), rgba(201,168,76,0.06))',
      borderRadius: '12px',
      border: '1px solid rgba(201,168,76,0.25)',
    }}>
      <p style={{ margin: '0 0 10px 0', fontWeight: 'bold', fontSize: '13px', color: '#4b0082' }}>
        💾 Save your chart:
      </p>
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
        <button style={btnStyle('#4b0082')} onClick={saveAsImage}>
          🖼️ Save as Image
        </button>
        <button style={btnStyle('#c9a84c')} onClick={saveAsText}>
          📄 Save as Text
        </button>
        {saved && <span style={{ alignSelf: 'center', color: '#4b0082', fontWeight: 'bold', fontSize: '13px' }}>✅ Saved!</span>}
      </div>
    </div>
  );
}
