[build]
  publish = "dist/public"
  command = "npm install && npm run build:client"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8.19.2"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run start"
  port = 3000
  publish = "dist/public"
